# P4_Florian_Cazac
## Transportation problem

1. Read an external file containing the parameters of a transportation problem LP problem
2. Different methods can be used to find the initial feasible solution for the problem:
    * Northwest corner rule
    * Minimum cost method
    * Minimum Row cost method
    * Vogel's method
3. the transportation simplex algorithm in an arbitrary transportation problem. 

In [64]:
import pandas as pd
import numpy as np

## Read a file containing the parameters of a transportation problem LP problem

In [65]:
filename = 'transportation_problem.csv'

In [66]:
data = pd.read_csv(filename, index_col=0)
supply = data['Supply'][:-1].to_numpy()
demand = data.loc["Demand"].drop("Supply").to_numpy()
cost = data.iloc[:-1, :-1].to_numpy()


## Different methods can be used to find the initial feasible solution

### 1. Northwest corner rule

In [67]:
# North West Corner Method

def north_west_corner(supply, demand):
    i = 0
    j = 0
    allocation = np.zeros((supply.size, demand.size))
    while i < supply.size and j < demand.size:
        if supply[i] < demand[j]:
            allocation[i][j] = supply[i]
            demand[j] -= supply[i]
            i += 1
        else:
            allocation[i][j] = demand[j]
            supply[i] -= demand[j]
            j += 1
    return allocation

def get_cost(allocation, cost):
    return np.sum(allocation * cost)

In [68]:
north_west_corner_allocation = north_west_corner(supply, demand)
print("North West Corner Method")
print(north_west_corner_allocation)
print("\nCost: ", get_cost(north_west_corner_allocation, cost))

North West Corner Method
[[400. 100.   0.   0.]
 [  0. 700.   0.   0.]
 [  0. 100. 200. 500.]]

Cost:  14200.0


### 2. Minimum cost method

### 3. Minimum Row cost method

### 4. Vogel's method