# P4_Florian_Cazac
## Transportation problem

1. Read an external file containing the parameters of a transportation problem LP problem
2. Different methods can be used to find the initial feasible solution for the problem:
    * Northwest corner rule
    * Minimum cost method
    * Minimum Row cost method
    * Vogel's method
3. the transportation simplex algorithm in an arbitrary transportation problem. 

In [177]:
import pandas as pd
import numpy as np

## Read a file containing the parameters of a transportation problem LP problem

In [178]:
filename = 'transportation_problem.csv'

In [179]:
data = pd.read_csv(filename, index_col=0)
supply = data['Supply'][:-1].to_numpy()
demand = data.loc["Demand"].drop("Supply").to_numpy()
cost = data.iloc[:-1, :-1].to_numpy()


## Different methods can be used to find the initial feasible solution

### 1. Northwest corner rule

In [180]:
# North West Corner Method

def north_west_corner(supply, demand):
    supply = supply.copy()
    demand = demand.copy()
    i = 0
    j = 0
    allocation = np.zeros((supply.size, demand.size))
    while i < supply.size and j < demand.size:
        if supply[i] < demand[j]:
            allocation[i][j] = supply[i]
            demand[j] -= supply[i]
            i += 1
        else:
            allocation[i][j] = demand[j]
            supply[i] -= demand[j]
            j += 1
    return allocation

def get_cost(allocation, cost):
    return np.sum(allocation * cost)

In [181]:
north_west_corner_allocation = north_west_corner(supply, demand)
print("NorthWest Corner Method")
print(north_west_corner_allocation)
print("\nCost: ", get_cost(north_west_corner_allocation, cost))

NorthWest Corner Method
[[400. 100.   0.   0.]
 [  0. 700.   0.   0.]
 [  0. 100. 200. 500.]]

Cost:  14200.0


### 2. Minimum cost method

In [182]:
# Minimum Cost Method

def minimum_cost_method(supply, demand, costs):
    supply = supply.copy()
    demand = demand.copy()
    allocation = np.zeros_like(costs, dtype=float)  # Allocation matrix
    
    # Get the indices of costs in ascending order
    cost_indices = np.dstack(np.unravel_index(np.argsort(costs, axis=None), costs.shape))[0]
    
    for i, j in cost_indices:
        if supply[i] == 0 or demand[j] == 0:  # Skip exhausted rows/columns
            continue
        
        # Allocate as much as possible to the minimum cost cell
        allocated = min(supply[i], demand[j])
        allocation[i, j] = allocated
        supply[i] -= allocated
        demand[j] -= allocated
    
    return allocation


In [183]:
minimum_cost_allocation = minimum_cost_method(supply, demand, cost)
print("\nMinimum Cost Method")
print(minimum_cost_allocation)
print("\nCost: ", get_cost(minimum_cost_allocation, cost))


Minimum Cost Method
[[300.   0. 200.   0.]
 [  0. 700.   0.   0.]
 [100. 200.   0. 500.]]

Cost:  12000.0


### 3. Minimum Row cost method

### 4. Vogel's method